### DISCUSSION TITLE
Deadlock with Sequel 5.52 and ActiveSupport Core Extensions under Ruby < 3.1

### DISCUSSION THREAD

**Discussion by rgalanakis** [jeremyevans/sequel#1816] [General]
I was originally going to file this as a bug, but I couldn't in good conscience file a bug against Sequel involving Active Support core extensions, and I don't think it has a good solution other than 'do not install the activesupport class core extensions'. I figure it was a nice writeup and is good reference so didn't want to get rid of it and figured the mailing list is a good place. And if you can think of a solution to make Sequel subclasses and ActiveSupport core extensions work well together pre-Ruby 3.1, that'd be swell (though it actually wouldn't affect any of our current projects so nbd to me).

### Complete Description of Issue

Sequel's Subclasses plugin was recently updated to make use of Ruby 3.1's `Object.subclasses` method in https://github.com/jeremyevans/sequel/commit/185efe54047a6c912555651523726f9929451589

It did this by removing the Sequel-land `subclasses` method, so `descendants` calls the built-in `subclasses` method. It checks whether to use this based on `Object.respond_to?(:subclasses)`.

If ActiveSupport core extensions are installed, they will *also* install subclasses/descendants methods. This code has churned recently due to the Classes.descendants changes ([I saw you were involved in the discussion](https://bugs.ruby-lang.org/issues/14394#note-38)), but I think it's still an issue at HEAD.

Under Ruby 3.1, this isn't a problem. ActiveSupport doesn't install either subclasses nor descendants; Sequel doesn't install subclasses; Sequel descendants uses Ruby's built-in subclasses.

Under earlier Ruby, Sequel 5.51 and earlier, and ActiveSupport, this also wasn't an issue- ActiveSupport installs its methods, then using the `subclasses` plugin would replace both of them with Sequel's implementation.

However under earlier Ruby, Sequel 5.52, and ActiveSupport, what happens is:
- ActiveSupport installs subclasses and descendants methods
- Sequel checks `Object.respond_to?(:subclasses)`. It does (because the core extensions). Sequel only overrides `descendants`.
- Sequel's `descendants` calls ActiveSupport's `subclasses`. ActiveSupport `subclasses` calls `descendants`, which goes back into Sequel's `descendants`, causing a deadlock in `Sequel.synchronize` (it would eventually stack overflow if not for that).

### Simplest Possible Self-Contained Example Showing the Bug

```rb
require "active_support"
require "active_support/core_ext"
require 'sequel'

module MyProj; end

MyProj::Model = Class.new(Sequel::Model)
MyProj::Model.def_Model(MyProj)
MyProj::Model.plugin(:subclasses)

class MyProj::Model; end
puts MyProj::Model.descendants
```

### Full Backtrace of Exception (if any)

```
ThreadError: deadlock; recursive locking

  0) Webhookdb::Postgres::ModelUtilities an extended class has a method for fetching a subclass by its full name
     Failure/Error:
       return self.descendents.find do |cl|
         cl.name&.end_with?(classname)
       end

     ThreadError:
       deadlock; recursive locking
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/core.rb:316:in `synchronize'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/core.rb:316:in `synchronize'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/plugins/subclasses.rb:64:in `descendants'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/class/subclasses.rb:33:in `subclasses'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/plugins/subclasses.rb:64:in `block in descendants'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/core.rb:316:in `synchronize'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/core.rb:316:in `synchronize'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sequel-5.52.0/lib/sequel/plugins/subclasses.rb:64:in `descendants'
     # ./lib/webhookdb/postgres/model_utilities.rb:81:in `by_name'
     # ./spec/webhookdb/postgres/model_utilities_spec.rb:65:in `block (2 levels) in <top (required)>'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # ./lib/webhookdb/spec_helpers/postgres.rb:39:in `block in included'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/appydays-0.1.2/lib/appydays/loggable/spec_helpers.rb:15:in `block in included'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/webmock-3.12.2/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/rob/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # /Users/rob/.rbenv/versions/2.7.5/bin/rspec:23:in `load'
     # /Users/rob/.rbenv/versions/2.7.5/bin/rspec:23:in `<main>'
```
