### DISCUSSION TITLE
pg_range extension with fixture_dependencies

### DISCUSSION THREAD

**Discussion by adam12** [jeremyevans/sequel#1884] [General]
Hi, Jeremy et all,

I've had to create this workaround for creating a fixture (via fixture_dependencies) that creates a model record which has a `tsrange` field.

I'm wondering if this is something that should be done by the `pg_range` extension when creating the SQL expression? I know this is a special case, so perhaps this is the best I'm going to get with YAML as the base.

Thoughts?

```yaml
# fixture
one:
  date_range: ["2022-06-01 00:00:00", "2022-06-30 23:59:59"]
```

```ruby

DB.extension :pg_range

class MyModel < Sequel::Model
  # date_range is a `tsrange` column type
  def date_range=(value)
    # Cast to Range here, since the Fixture provides an Array
    value = Range.new(*value) if value.is_a?(Array)
    super(value)
  end
end
```

**Comment by jeremyevans** [comment]
You can provide a string in the same format that PostgreSQL uses, since pg_range already handles that.  If that works, I think it's better than adding support for arrays.  Can you try that?

**Reply by adam12** [reply]
Indeed, the string format that PostgreSQL accepts worked fine!

This updated the fixture to look like this :

```yaml
# fixture
one:
  date_range: "[2022-06-01 00:00:00, 2022-06-30 23:59:59]"
```

Thanks!

EDIT: The brackets have a significance.
